src/LineStorm/MediaBundle/Form/MediaMultipleFormType.php
<?php

namespace LineStorm\MediaBundle\Form;

use LineStorm\MediaBundle\Form\DataTransformer\MediaTransformer;
use LineStorm\MediaBundle\Media\MediaManager;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

/**
 * Class MediaFormType
 *
 * @package LineStorm\MediaBundle\Form
 */
class MediaMultipleFormType extends AbstractType
{

    /**
     * MediaManager
     *
     * @var MediaManager
     */
    protected $mediaManager;

    /**
     * @param MediaManager $mediaManager
     */
    function __construct(MediaManager $mediaManager)
    {
        $this->mediaManager = $mediaManager;
    }

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('media', 'collection', array(
                'type' => new MediaFormType($this->mediaManager),
                'allow_add' => true,
                'allow_delete' => true,
            ))
        ;
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'linestorm_cms_form_media_multiple';
    }
}

src/LineStorm/MediaBundle/Form/Type/MediaEntityType.php
<?php

namespace LineStorm\MediaBundle\Form\Type;

use LineStorm\MediaBundle\Form\DataTransformer\MediaEntityTransformer;
use LineStorm\MediaBundle\Media\MediaManager;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

/**
 * Class MediaEntityType
 * @package LineStorm\MediaBundle\Form\Type
 */
class MediaEntityType extends AbstractType
{
    /**
     * @var MediaManager
     */
    protected $mediaManager;

    /**
     * @var MediaEntityTransformer
     */
    protected $transformer;

    /**
     * @param MediaManager $mediaManager
     */
    function __construct(MediaManager $mediaManager)
    {
        $this->mediaManager = $mediaManager;
        $this->transformer = new MediaEntityTransformer($this->mediaManager);
    }

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->addModelTransformer($this->transformer);
    }


    /**
     * {@inheritdoc}
     */
    public function finishView(FormView $view, FormInterface $form, array $options)
    {
        $media = $this->transformer->reverseTransform($view->vars['value']);
        $view->vars['media'] = $media;
    }

    /**
     * {@inheritdoc}
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'class' => $this->mediaManager->getDefaultProviderInstance()->getEntityClass(),
            'property' => 'title',
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getParent()
    {
        return 'hidden';
    }

    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'mediaentity';
    }
}

src/LineStorm/MediaBundle/Controller/Admin/CategoryController.php
<?php

namespace LineStorm\MediaBundle\Controller\Admin;

use LineStorm\MediaBundle\Model\MediaCategory;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * Class AdminController
 *
 * @package LineStorm\MediaBundle\Controller
 */
class CategoryController extends Controller
{

    /**
     * Edit a media entity
     *
     * @param $id
     *
     * @throws AccessDeniedException
     * @throws NotFoundHttpException
     * @return Response
     */
    public function editAction($id)
    {
        $user = $this->getUser();
        if(!($user instanceof UserInterface) || !($user->hasGroup('admin')))
        {
            throw new AccessDeniedException();
        }

        $modelManager = $this->get('linestorm.cms.model_manager');
        $repo         = $modelManager->get('media_category');

        $category = $repo->find($id);

        if(!($category instanceof MediaCategory))
        {
            throw $this->createNotFoundException("Media Category Not Found");
        }

        $form = $this->createForm('linestorm_cms_form_media_category', $category, array(
            'action' => $this->generateUrl('linestorm_cms_module_media_api_put_category', array('id' => $category->getId())),
            'method' => 'PUT',
        ));

        return $this->render('LineStormMediaBundle:Category:edit.html.twig', array(
            'category' => $category,
            'form'     => $form->createView(),
        ));
    }

    /**
     * Create a media entity
     *
     * @return Response
     * @throws AccessDeniedException
     */
    public function newAction()
    {
        $user = $this->getUser();
        if(!($user instanceof UserInterface) || !($user->hasGroup('admin')))
        {
            throw new AccessDeniedException();
        }

        $modelManager = $this->get('linestorm.cms.model_manager');
        $class        = $modelManager->getEntityClass('media_category');

        $form = $this->createForm('linestorm_cms_form_media_category', new $class(), array(
            'action' => $this->generateUrl('linestorm_cms_module_media_api_post_category'),
            'method' => 'POST',
        ));

        return $this->render('LineStormMediaBundle:Category:new.html.twig', array(
            'image' => null,
            'form'  => $form->createView(),
        ));
    }


    /**
     * Upload a media entity
     *
     * @return Response
     * @throws AccessDeniedException
     */
    public function uploadAction()
    {
        $user = $this->getUser();
        if (!($user instanceof UserInterface) || !($user->hasGroup('admin')))
        {
            throw new AccessDeniedException();
        }


        $code = 201;
        try
        {
            $media = $this->doUpload();
        } catch (MediaFileAlreadyExistsException $e)
        {
            $media = $e->getEntity();
            $code  = 200;
        } catch (\Exception $e)
        {
            $view = View::create(array(
                'error' => $e->getMessage(),
            ), 400);
            $view->setFormat('json');

            return $this->get('fos_rest.view_handler')->handle($view);
        }

        $api = array(
            'edit' => $this->generateUrl('linestorm_cms_module_media_api_put_media', array('id' => $media->getId())),
        );
        $doc = new \LineStorm\MediaBundle\Document\Media($media, $api);
        $view = View::create($doc, $code);
        $view->setFormat('json');

        return $this->get('fos_rest.view_handler')->handle($view);
    }

    /**
     * Upload an item for a entity we are editing
     *
     * @param $id
     *
     * @return Response
     * @throws AccessDeniedException
     * @throws HttpException
     * @throws NotFoundHttpException
     */
    public function uploadEditAction($id)
    {
        $user = $this->getUser();
        if (!($user instanceof UserInterface) || !($user->hasGroup('admin')))
        {
            throw new AccessDeniedException();
        }

        $mediaManager = $this->get('linestorm.cms.media_manager');
        $image        = $mediaManager->find($id);

        if (!($image instanceof Media))
        {
            throw $this->createNotFoundException("Image Not Found");
        }

        $code = 201;
        try
        {
            $image = $this->doUpload($image);
        } catch (MediaFileAlreadyExistsException $e)
        {
            $code = 200;
        } catch (HttpException $e)
        {
            $view = View::create($e);
            $view->setFormat('json');

            return $this->get('fos_rest.view_handler')->handle($view);
        } catch (\Exception $e)
        {
            throw new HttpException(400, 'Upload Invalid', $e);
        }

        $view = View::create(new \LineStorm\MediaBundle\Document\Media($image), $code);
        $view->setFormat('json');

        return $this->get('fos_rest.view_handler')->handle($view);
    }


    /**
     * Handle a file upload
     *
     * @param Media|null $entity The entity to store into
     *
     * @return Media
     * @throws HttpException
     */
    private function doUpload($entity = null)
    {
        $mediaManager = $this->get('linestorm.cms.media_manager');

        $request = $this->getRequest();
        $files   = $request->files->all();

        $totalFiles = count($files);

        // only allow single uploads
        if ($totalFiles === 1)
        {
            /* @var $file \Symfony\Component\HttpFoundation\File\UploadedFile */
            $file = array_shift($files);

            if ($file->isValid())
            {
                $media = $mediaManager->store($file, $entity);

                if (!($media instanceof Media))
                {
                    throw new HttpException(400, 'Upload Invalid');
                }

                return $media;
            }
            else
            {
                switch ($file->getError())
                {
                    case UPLOAD_ERR_INI_SIZE:
                        throw new HttpException(400, 'Upload Invalid: File too large for server');
                        break;
                    case UPLOAD_ERR_FORM_SIZE:
                        throw new HttpException(400, 'Upload Invalid: File too large for form');
                        break;
                    case UPLOAD_ERR_PARTIAL:
                        throw new HttpException(400, 'Upload Invalid: Only a partial file was recieved');
                        break;
                    case UPLOAD_ERR_NO_FILE:
                        throw new HttpException(400, 'Upload Invalid: No file given');
                        break;
                    case UPLOAD_ERR_NO_TMP_DIR:
                        throw new HttpException(400, 'Upload Invalid: Unable to store (1)');
                        break;
                    case UPLOAD_ERR_CANT_WRITE:
                        throw new HttpException(400, 'Upload Invalid: Unable to store (2)');
                        break;
                    case UPLOAD_ERR_EXTENSION:
                        throw new HttpException(400, 'Upload Invalid: Invalid Extension');
                        break;
                }
            }
        }
        else
        {
            throw new HttpException(400, 'Upload Invalid: Too Many Files.');
        }
    }
}

src/LineStorm/MediaBundle/Resources/views/Category/edit.html.twig
{% extends 'LineStormMediaBundle:Category:form.html.twig' %}

{% block page_title %}Edit Media Category{% endblock %}
{% block page_desc %}{% endblock %}

{% block module_bread %}
    <li><a href="#" class="active">Edit Category</a></li>
{% endblock %}

{% block module %}

    {{ form_start(form, {attr: { class: 'media-api-save', 'data-count': category.media|length, 'data-category-id': category.id } }) }}
        {{ form_row(form.name) }}

        <div class="form-group">
            {{ form_label(form.parent) }}
            <div class="col-sm-10">
                {{ form_widget(form.parent) }}

                {% set parent_node = null %}
                {% if category.parent != null %}
                    {% set parent_node = category.parent.id %}
                {% endif %}

                {{
                    include('LineStormMediaBundle:Form:multiple.html.twig', {
                        flat: true,
                        init_node: parent_node,
                        exclude_nodes: category.id,
                        input: '#linestorm_cms_form_media_category_parent'
                    })
                }}
            </div>
        </div>


        <div class="form-group">
            <div class="col-sm-12">

                <button type="submit" class="btn btn-default" data-url="{{ url('linestorm_cms_module_media_api_put_category', {id: category.id}) }}">
                    <i class="fa-save"></i> Save
                </button>

                <button type="button" class="btn btn-danger media-form-delete" data-url="{{ path('linestorm_cms_module_media_api_delete_category', {id: category.id}) }}">
                    <i class="fa-trash-o"></i> Delete
                </button>
            </div>
        </div>

        {{ form_widget(form.media) }}
    {{ form_end(form) }}
{% endblock %}

src/LineStorm/MediaBundle/Resources/views/Category/form.html.twig
{% extends 'LineStormMediaBundle::layout.html.twig' %}

{% block head %}
    {% block requirejs %}
        {{
            include('LineStormCmsBundle::requirejs.html.twig', {
                requirejs_module: ['cms_main', 'cms_media', 'cms_media_treebrowser']
            })
        }}
    {% endblock %}

    {% stylesheets
        filter="compass" output="cms/media/css/media.css"
        "@LineStormMediaBundle/Resources/assets/sass/media.scss"
    %}
        <link rel="stylesheet" href="{{ asset_url }}" />
    {% endstylesheets %}
{% endblock %}

{% block module %}

    {% include 'LineStormMediaBundle:Form:multiple.html.twig' %}

{% endblock %}

src/LineStorm/MediaBundle/Resources/views/Category/new.html.twig
{% extends 'LineStormMediaBundle:Category:form.html.twig' %}

{% block page_title %}New Media Category{% endblock %}
{% block page_desc %}{% endblock %}

{% block module_bread %}
    <li><a href="#" class="active">New Category</a></li>
{% endblock %}

{% block module %}

    {{ form_start(form, {attr: { class: 'media-api-save', 'data-count': 0 } }) }}
        {{ form_row(form.name) }}

        <div class="form-group">
            {{ form_label(form.parent) }}
            <div class="col-sm-10">
                {{ form_widget(form.parent) }}
                {{
                    include('LineStormMediaBundle:Form:multiple.html.twig', {
                        input: '#linestorm_cms_form_media_category_parent'
                    })
                }}
            </div>
        </div>


        <div class="form-group">
            <div class="col-sm-12">

                <button type="submit" class="btn btn-default" data-url="{{ url('linestorm_cms_module_media_api_post_category') }}">
                    <i class="fa-save"></i> Save
                </button>
            </div>
        </div>

        {{ form_widget(form.media) }}
    {{ form_end(form) }}
{% endblock %}